name = "GinvLabRegistry"
uuid = "01251907-5da5-4648-88a5-e27f7a11fa45"
repo = "git@github.com:GinvLab/GinvLabRegistry"
description = "G⁻¹Lab Julia registry"

[packages]
0631ba50-6b23-11e9-3fc3-378508ba069a = { name = "EikonalSolvers", path = "E/EikonalSolvers" }
5ad9ae14-893c-4be5-bc0a-7005514a6e19 = { name = "MagGravPoly", path = "M/MagGravPoly" }
f2cc81fa-a164-11e9-3f65-e3f851c759e3 = { name = "SeismicWaves", path = "S/SeismicWaves" }
